// Code generated by MockGen. DO NOT EDIT.
// Source: table.describe.go

// Package mock is a generated GoMock package.
package mock

import (
	aws "github.com/aws/aws-sdk-go/aws"
	gomock "github.com/golang/mock/gomock"
	dynamo "github.com/guregu/dynamo"
	reflect "reflect"
)

// MockDescribeTable is a mock of DescribeTable interface
type MockDescribeTable struct {
	ctrl     *gomock.Controller
	recorder *MockDescribeTableMockRecorder
}

// MockDescribeTableMockRecorder is the mock recorder for MockDescribeTable
type MockDescribeTableMockRecorder struct {
	mock *MockDescribeTable
}

// NewMockDescribeTable creates a new mock instance
func NewMockDescribeTable(ctrl *gomock.Controller) *MockDescribeTable {
	mock := &MockDescribeTable{ctrl: ctrl}
	mock.recorder = &MockDescribeTableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDescribeTable) EXPECT() *MockDescribeTableMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockDescribeTable) Run() (dynamo.Description, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(dynamo.Description)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run
func (mr *MockDescribeTableMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDescribeTable)(nil).Run))
}

// RunWithContext mocks base method
func (m *MockDescribeTable) RunWithContext(ctx aws.Context) (dynamo.Description, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithContext", ctx)
	ret0, _ := ret[0].(dynamo.Description)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunWithContext indicates an expected call of RunWithContext
func (mr *MockDescribeTableMockRecorder) RunWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithContext", reflect.TypeOf((*MockDescribeTable)(nil).RunWithContext), ctx)
}
