// Code generated by MockGen. DO NOT EDIT.
// Source: table.delete.go

// Package mock is a generated GoMock package.
package mock

import (
	aws "github.com/aws/aws-sdk-go/aws"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockDeleteTable is a mock of DeleteTable interface
type MockDeleteTable struct {
	ctrl     *gomock.Controller
	recorder *MockDeleteTableMockRecorder
}

// MockDeleteTableMockRecorder is the mock recorder for MockDeleteTable
type MockDeleteTableMockRecorder struct {
	mock *MockDeleteTable
}

// NewMockDeleteTable creates a new mock instance
func NewMockDeleteTable(ctrl *gomock.Controller) *MockDeleteTable {
	mock := &MockDeleteTable{ctrl: ctrl}
	mock.recorder = &MockDeleteTableMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeleteTable) EXPECT() *MockDeleteTableMockRecorder {
	return m.recorder
}

// Run mocks base method
func (m *MockDeleteTable) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run
func (mr *MockDeleteTableMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockDeleteTable)(nil).Run))
}

// RunWithContext mocks base method
func (m *MockDeleteTable) RunWithContext(ctx aws.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunWithContext", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunWithContext indicates an expected call of RunWithContext
func (mr *MockDeleteTableMockRecorder) RunWithContext(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunWithContext", reflect.TypeOf((*MockDeleteTable)(nil).RunWithContext), ctx)
}
